version: '3.1'

services:

  mongo:
    image: mongo:5.0.0-rc3-focal

    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/db_files:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4

    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql/db_files:/var/lib/mysql

  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'type-orm'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./postgres/db_files:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: 'user'
      PMA_PASSWORD: 'password'
      PHP_UPLOAD_MAX_FILESIZE: '100MB'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
